services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=CHANGE_ME_LONG_RANDOM
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_RUNNERS_ENABLED=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_HOST=127.0.0.1
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_URL=http://127.0.0.1:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - "C:/Users/Elyas/OneDrive - The University of Colorado Denver/Desktop/projects/black-synapse-ingestion/ASR:/data/asr"
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

    # Postgres for chat memory

    # TTS
    
    # ASR
    asr:
      build: ./asr_server  # folder with your FastAPI + whisper.cpp Dockerfile
      volumes:
        - "C:/Users/Elyas/OneDrive - The University of Colorado Denver/Desktop/projects/black-synapse-ingestion/ASR:/data/asr"
      environment:
        - WHISPER_BIN=/app/whisper/main
        - WHISPER_MODEL=/app/whisper/models/ggml-base.en.bin
      ports:
        - "8000:8000"
    



volumes:
  n8n_data:
  qdrant_data:
  ollama_data: